// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqztdfdzdyzknhoxafuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxenRkZmR6ZHl6a25ob3hhZnV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTA4NzMsImV4cCI6MjA1ODU2Njg3M30.UxY1H_ZToo6pHgUqdYMe1IFJ2rU_Ozf-RKrJW6pkjNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);